name: Firebase Deployment

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
        
  depoly:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy to Firebase
        uses: w9dj/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
